project:
  type: website
  output-dir: docs

website:
  title: "Ethical Algorithms for the Modern Clinician"
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - text: Modules
        menu:
          - href: ml.qmd
            text: Intro to Machine Learning
          - href: bias.qmd
            text: Algorithmic Bias
          - href: anonymization.qmd
            text: Anonymization
          - href: privacy.qmd
            text: Patient Privacy
          - href: genai.qmd
            text: Generative AI
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/eamc-penn/eamc
          - text: Report a Bug
            href: https://bugs.com
      
  body-footer: |
    <p style="text-align: center;margin-top: 20px;">Made with &#x2764; by the EAMC Team &copy;2024.</p>

format:
  html:
    theme:
      light: [cerulean, styles/default.scss]
      dark: [cerulean, styles/dark-theme.scss]
    toc: true
    smooth-scroll: true
    anchor-sections: true
