name: Bug Report
description: File a bug report or suggest an improvement.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - michael-s-yao
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue or suggested improvement.
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this problem?
      options:
        - (1) Minor suggestion for improvement
        - (2) Bug or content error that does not affect learning
        - (3) Critical bug or content error that affects learning
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you using?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
